[package]
name = "mas-tower"
description = "Tower layers used by the Matrix Authentication Service"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
http.workspace = true
opentelemetry-http.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
pin-project-lite.workspace = true
tower.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
